marklogic/marklogic-mule-connector

- README.md
> Updated broken Wiki link in README.md

- src/main/java/com/marklogic/mule/extension/connector/internal/connection/MarkLogicConnector.java
- src/main/java/com/marklogic/mule/extension/connector/internal/operation/MarkLogicInsertionBatcher.java
- src/main/java/com/marklogic/mule/extension/connector/internal/operation/MarkLogicOperations.java
- src/main/java/com/marklogic/mule/extension/connector/internal/result/resultset/MarkLogicResultSetIterator.java
Could one of you please give an eye test to confirm these changes, for syntax?  This addresses the latest Sonar findings.
If it passes your eye test, then please feel free to merge afterward.
> Clay: cleaned up code based on Sonar findings

- src/main/java/com/marklogic/mule/extension/connector/internal/connection/MarkLogicConnection.java
- src/main/java/com/marklogic/mule/extension/connector/internal/connection/provider/MarkLogicConnectionProvider.java
- src/main/java/com/marklogic/mule/extension/connector/internal/operation/InsertionBatcherContext.java
- src/main/java/com/marklogic/mule/extension/connector/internal/operation/MarkLogicInsertionBatcher.java
- src/main/java/com/marklogic/mule/extension/connector/internal/operation/MarkLogicOperations.java
- src/main/java/com/marklogic/mule/extension/connector/internal/result/resultset/MarkLogicResultSetIterator.java
- src/test/java/com/marklogic/mule/extension/connector/MarkLogicOperationsTestCase.java
- src/test/java/com/marklogic/mule/extension/connector/internal/connection/MarkLogicConnectionTest.java
- src/test/java/com/marklogic/mule/extension/connector/internal/connection/provider/MarkLogicConnectionProviderTest.java
- src/test/java/com/marklogic/mule/extension/connector/internal/operation/MarkLogicOperationTest.java
The main challenge was addressing a few constructors we had that accepted 10 or so arguments. To address that in each case, I moved all the args into a separate class, and where appropriate, I added "with" methods to allow an instance of the class to be easily constructed and populated with only the desired args.
> Fixed remaining code smells

- src/main/java/com/marklogic/mule/extension/connector/internal/connection/MarkLogicConnection.java
Found by sonarqube 8, but not 9, but seem legit.
> Two more smells

- pom.xml
Couple other fixes as well:
- Removed unnecessary pluginRepositories block
- Changed tag to HEAD since current tag value does not yet exist
> Removing commented sections in pom

- src/test/java/com/marklogic/mule/extension/AbstractFlowTester.java
- src/test/java/com/marklogic/mule/extension/EvalJavaScriptTest.java
- src/test/java/com/marklogic/mule/extension/ReadAndWriteDocumentTest.java
- src/test/java/com/marklogic/mule/extension/ReadDocumentWithMetadataTest.java
- src/test/java/com/marklogic/mule/extension/SearchDocumentsCombinedQueriesTest.java
- src/test/java/com/marklogic/mule/extension/SearchDocumentsSerializedCtsQueriesTest.java
- src/test/java/com/marklogic/mule/extension/SearchDocumentsStringQueriesTest.java
- src/test/java/com/marklogic/mule/extension/SearchDocumentsStructuredQueriesTest.java
- src/test/java/com/marklogic/mule/extension/SearchDocumentsWithMetadataTest.java
- src/test/java/com/marklogic/mule/extension/SearchDocumentsWithOptionsTest.java
- src/test/java/com/marklogic/mule/extension/WriteDocumentTest.java
- src/test/resources/eval-javascript.xml
- src/test/resources/prepare-database-flow.xml
- src/test/resources/read-and-write-document.xml
- src/test/resources/write-document.xml
This consolidates the prepare-database flow and makes it's use programmatic.
> Refactoring prepare-database

- CONTRIBUTING.md
- pom.xml
- src/test/munit/batch-read-write-test-suite.xml
I'm not great with Maven, so there's a good chance there are improvements to be made to the pom file.
> Adds an MUnit batch test and updates the POM to be able to run the test.

- src/main/java/com/marklogic/mule/extension/ConnectionProvider.java
No tests yet as we don't have the infrastructure for these yet.
> DEVEXP-577 Added saml/kerberos support

- CONTRIBUTING.md
- docs/connection-guide.md
- docs/index.md
- src/main/java/com/marklogic/mule/extension/Configuration.java
- src/main/java/com/marklogic/mule/extension/ConnectionProvider.java
- src/main/java/com/marklogic/mule/extension/api/AuthenticationType.java
- src/test/resources/insecure-ssl.xml
- src/test/resources/read-and-write-document.xml
- src/test/resources/read-document-with-metadata.xml
- src/test/resources/search-documents-combined-queries.xml
- src/test/resources/search-documents-serialized-cts-queries.xml
- src/test/resources/search-documents-string-queries.xml
- src/test/resources/search-documents-structured-queries.xml
- src/test/resources/search-documents-with-metadata.xml
- src/test/resources/search-documents-with-options.xml
- src/test/resources/write-document.xml
- src/test/studio-workspace/marklogicQuickstart/src/main/mule/multiple-example-flows.xml
Other enhancements:
- Removed the unnecessary `configId` parameter (hence the changes to a bunch of test flows).
- Added "Password" annotation where appropriate.
> DEVEXP-631 Added docs for making a connection

- docs/writing.md
- src/main/java/com/marklogic/mule/extension/Operations.java
- src/test/resources/write-document.xml
I don't think there's a ton to say here as it's fairly straightforward. "Reading documents" will require a lot more explanation due to the different types of queries we support.
> DEVEXP-633 Added docs for writing documents

- CONTRIBUTING.md
- pom.xml
This is now appearing in the Sonar reports, and it's passing the coverage check with 87.4% coverage.
> Added jacoco for code coverage

- src/main/java/com/marklogic/mule/extension/AbstractPagingProvider.java
- src/main/java/com/marklogic/mule/extension/ReadPagingProvider.java
- src/main/java/com/marklogic/mule/extension/api/DocumentAttributes.java
- src/main/java/com/marklogic/mule/extension/api/ErrorType.java
- src/main/java/com/marklogic/mule/extension/api/ExecuteErrorsProvider.java
- src/test/java/com/marklogic/mule/extension/AbstractFlowTester.java
Realized I shouldn't have broken out the fields of DMH. Also renamed the private methods in DA to emphasize that it knows how to serialize itself to JSON and deserialize from JSON.
> Refactored DocumentAttributes to contain URI and DocumentMetadataHandle

- src/main/java/com/marklogic/mule/internal/QueryParameters.java
- src/main/java/com/marklogic/mule/internal/connection/provider/ConnectionProvider.java
- src/main/java/com/marklogic/mule/internal/extension/MarkLogicConnector.java
This should be the last of the code smells, unless they need us to do something about "demo".
> Address more code smells identified by CAM/SONAR.

- src/main/java/com/marklogic/mule/internal/ReadPagingProvider.java
I'm hopeful that this is the last of the updates to satisfy the CAM.
> Fix a logging smell.

- LICENSE.md
- LICENSE_HEADER.txt
- README.md
- examples/demo-project/pom.xml
- examples/demo-project/src/main/resources/log4j2.xml
- examples/demo-project/src/test/resources/log4j2-test.xml
- pom.xml
- src/main/java/com/marklogic/mule/connector/api/config/Configuration.java
- src/main/java/com/marklogic/mule/connector/api/extension/MarkLogicConnector.java
- src/main/java/com/marklogic/mule/connector/internal/operation/Operations.java
- src/main/java/com/marklogic/mule/connector/internal/operation/QueryParameters.java
- src/main/java/com/marklogic/mule/connector/internal/operation/ReadPagingProvider.java
- src/main/java/com/marklogic/mule/connector/internal/operation/WriteParameters.java
- src/main/java/com/marklogic/mule/connector/internal/provider/AuthenticationType.java
- src/main/java/com/marklogic/mule/connector/internal/provider/ConnectionProvider.java
- src/main/java/com/marklogic/mule/connector/internal/provider/ConnectionType.java
- src/main/java/com/marklogic/mule/connector/internal/provider/DocumentAttributes.java
- src/main/java/com/marklogic/mule/connector/internal/provider/DocumentFormat.java
- src/main/java/com/marklogic/mule/connector/internal/provider/HostnameVerifier.java
- src/main/java/com/marklogic/mule/connector/internal/provider/QueryFormat.java
- src/main/java/com/marklogic/mule/connector/internal/provider/QueryType.java
- src/test/java/com/marklogic/mule/extension/AbstractFlowTester.java
- src/test/java/com/marklogic/mule/extension/DocumentData.java
- src/test/java/com/marklogic/mule/extension/MetadataVerifier.java
- src/test/java/com/marklogic/mule/extension/SearchDocumentsWithMetadataTest.java
- src/test/java/com/marklogic/mule/extension/WriteDocumentTest.java
- src/test/studio-workspace/marklogicQuickstart/pom.xml
1) Updated the Mule Runtime to 4.3.0
2) Moved the Operations classes to the internal package
3) That meant I could move classes back to the internal package (sorry, I think I have it right this time)
4) Changed the Category to CERTIFIED
5) Added LICENSE.MD
6) Added an example line for logging MarkLogic in the example project. Also added a couple of logging lines.
> New set of changes based on the MuleSoft checklist

- src/main/java/com/marklogic/mule/connector/api/error/ErrorType.java
- src/main/java/com/marklogic/mule/connector/api/error/provider/ExecuteErrorsProvider.java
- src/main/java/com/marklogic/mule/connector/api/types/DocumentAttributes.java
- src/main/java/com/marklogic/mule/connector/internal/connection/provider/ConnectionProvider.java
- src/main/java/com/marklogic/mule/connector/internal/extension/MarkLogicConnector.java
- src/main/java/com/marklogic/mule/connector/internal/operation/Operations.java
- src/main/java/com/marklogic/mule/connector/internal/operation/ReadPagingProvider.java
I really think I'm getting close.
> One more package move for CAM.

- CONTRIBUTING.md
- pom.xml
- settings.xml
- src/test/munit/mtf-basic-connector-usage.xml
We will probably need to add to this, but it at least gets the proper plumbing in place.
> MTF testing setup, including a basic test suite.

- src/main/java/com/marklogic/mule/connector/internal/error/ErrorType.java
- src/main/java/com/marklogic/mule/connector/internal/error/provider/ExecuteErrorsProvider.java
- src/main/java/com/marklogic/mule/connector/internal/operation/WriteParameters.java
- src/test/munit/mtf-basic-connector-usage.xml
- src/test/munit/test-flows.xml
Improved the tests and extended them to exercise error handling.
> More work on the MTF test

- CONTRIBUTING.md
- settings.xml
- src/test/munit/mtf-basic-connector-usage.xml
- src/test/munit/test-flows.xml
- test-app/src/main/ml-config/security/users/mule2-read-user.json
- test-app/src/main/ml-config/security/users/mule2-test-user.json
Also, changed the switch for the MuleSoft repository password.
> Changing the MTF files to use the MarkLogic Mule VM

- CONTRIBUTING.md
- README.md
- pom.xml
Fixed a typo in CONTRIBUTING.
Updated the required Mule version in README
> Small pom change based on the checklist

- RELEASE_NOTES.md
- docs/technical-reference.md
- src/main/java/com/marklogic/mule/connector/internal/connection/provider/ConnectionProvider.java
> MLE-12104 Can now read release notes and a technical reference
